name: build BRLTTY for Windows

on:
  push:
    branches: [master, gh-actions-windows-build]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build_brltty:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: MINGW32
            arch: mingw-w64-i686
          - msystem: MINGW64
            arch: mingw-w64-x86_64
          - msystem: UCRT64
            arch: mingw-w64-ucrt-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            autoconf
            automake
            tcl
            awk
            bison
            git
            groff
            m4
            patch
            ${{ matrix.arch }}-pdcurses
            ${{ matrix.arch }}-icu
            ${{ matrix.arch }}-tcl
            ${{ matrix.arch }}-winpthreads-git
            ${{ matrix.arch }}-libiconv
            ${{ matrix.arch }}-toolchain
            ${{ matrix.arch }}-python
            ${{ matrix.arch }}-python-setuptools
            ${{ matrix.arch }}-cython

      - uses: actions/checkout@v3

      - name: Apply patches
        run: patch -p0 <"Windows/affinity.patch"

      - name: Configure build
        run: |
          ./autogen
          ./cfg-windows --prefix=/ --enable-relocatable-install --with-usb-package=winusb

      - name: Build BRLTTY
        run: |
          mingw32-make
          mingw32-make -C Documents

      - name: Install BRLTTY
        run: |
          mkdir -p install/{bin,etc,lib,python}
          mingw32-make install install-messages JAVA_JAR_DIR=/lib JAVA_JNI_DIR=/lib PYTHON_PREFIX="Python" INSTALL_ROOT="./install"
          cp Documents/brltty.conf install/etc/
          cp Programs/*.exe Programs/*.dll install/bin
          cp Bindings/Python/dist/* install/python/
          cp LICENSE-LGPL install/LICENSE-LGPL.txt
          cp Documents/*.csv install/etc/
          cp Windows/*.bat install/
          cp $MINGW_PREFIX/bin/libgcc_s*.dll $MINGW_PREFIX/bin/libiconv-2.dll $MINGW_PREFIX/bin/libpdcurses*.dll $MINGW_PREFIX/bin/libintl-8.dll install/bin/ 2>/dev/null || true
          cd install/
          rm -f "bin/brltty-config"
          rm -f "etc/brlapi.key"

      - uses: actions/upload-artifact@v4
        with:
          name: brltty-${{ matrix.msystem }}
          path: install
